'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {createDrivingRefresh,israelDate,PAGE}=require('./driving-refresh');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
const NOW=Date.parse('2026-10-02T09:30:00Z');
function harness(role='firefighter',crew='B'){
 const state=new Map(),root='stations/station_a';
 const profile=(name,role,c)=>({station:'station_a',full_name:name,role,crew:c,is_active:true});
 state.set(root+'/users/actor123',profile('איתי',role,crew));state.set(root+'/users/other123',profile('דניאל','firefighter','B'));state.set(root+'/users/foreign123',profile('יוסי','firefighter','A'));
 const snap=(path)=>({id:path.split('/').at(-1),exists:state.has(path),data:()=>structuredClone(state.get(path))});
 class Ref{constructor(path){this.path=path;}collection(n){return new Query(this.path+'/'+n);}async get(){return snap(this.path);}}
 class Query{constructor(path,filters=[],orders=[],cap=Infinity,after=null){Object.assign(this,{path,filters,orders,cap,after});}doc(id){return new Ref(this.path+'/'+id);}where(k,op,v){return new Query(this.path,[...this.filters,[k,op,v]],this.orders,this.cap,this.after);}orderBy(k,dir){return new Query(this.path,this.filters,[...this.orders,[k,dir]],this.cap,this.after);}limit(cap){return new Query(this.path,this.filters,this.orders,cap,this.after);}startAfter(...after){return new Query(this.path,this.filters,this.orders,this.cap,after);}async get(){let keys=[...state.keys()].filter(p=>p.startsWith(this.path+'/')&&!p.slice(this.path.length+1).includes('/'));keys=keys.filter(p=>this.filters.every(([k,op,v])=>{const value=state.get(p)[k];return op==='=='?value===v:op==='>='?value>=v:value<=v;}));const values=p=>this.orders.map(([k])=>k==='__name__'?p.split('/').at(-1):state.get(p)[k]);const compare=(a,b)=>{for(let i=0;i<this.orders.length;i++){const sign=this.orders[i][1]==='desc'?-1:1;if(a[i]!==b[i])return (a[i]<b[i]?-1:1)*sign;}return 0;};keys.sort((a,b)=>compare(values(a),values(b)));if(this.after)keys=keys.filter(p=>compare(values(p),this.after)>0);return {docs:keys.slice(0,this.cap).map(snap)};}}
 const db={collection:p=>new Query(p),async runTransaction(fn){let written=false;const writes=[];const tx={get:async ref=>{assert.equal(written,false,'no reads after writes');return ref instanceof Query?ref.get():snap(ref.path);},create:(ref,value)=>{written=true;assert.equal(state.has(ref.path),false);writes.push([ref.path,value]);},update:(ref,value)=>{written=true;assert.equal(state.has(ref.path),true);writes.push([ref.path,{...state.get(ref.path),...value}]);}};const result=await fn(tx);for(const [path,value]of writes)state.set(path,structuredClone(value));return result;}};
 const service=createDrivingRefresh({db,HttpsError,clock:()=>NOW});const req=data=>({auth:{uid:'actor123',token:{stationId:'station_a',role}},data});
 const seed=(rid,uid,c,hours,date='2026-10-02')=>state.set(root+'/driving_refresh_reports/'+rid,{uid,name:'נהג',crew:c,hours,vehicle:'משאית',revision:1,created_at:date+'T08:00:00.000Z',local_date:date});
 return {service,req,state,root,seed};
}
const report={request_id:'request_123456',vehicle:'משאית 12',hours:3};
test('Israel date uses local midnight',()=>assert.equal(israelDate(Date.parse('2026-10-01T22:30:00Z')),'2026-10-02'));
test('own yearly indicator derives from server year, not client clock',async()=>{const h=harness();assert.equal((await h.service.context(h.req({}))).annual,false);h.seed('report_sep123','actor123','B',3,'2026-09-28');const ctx=await h.service.context(h.req({}));assert.equal(ctx.annual,true);assert.equal(ctx.year,'2026');});
test('new report uses live identity and server clock; retry is idempotent',async()=>{const h=harness();const a=await h.service.save(h.req(report));const b=await h.service.save(h.req(report));assert.equal(b.replayed,true);assert.equal(b.id,a.id);const r=h.state.get(h.root+'/driving_refresh_reports/'+a.id);assert.equal(r.uid,'actor123');assert.equal(r.name,'איתי');assert.equal(r.crew,'B');assert.equal(r.created_at,new Date(NOW).toISOString());assert.equal([...h.state.keys()].filter(p=>p.includes('/edits/')).length,1);});
test('same request ID with a changed payload rejected',async()=>{const h=harness();await h.service.save(h.req(report));await assert.rejects(h.service.save(h.req({...report,hours:4})),{code:'already-exists'});});
test('multiple independent reports in one day accepted',async()=>{const h=harness();await h.service.save(h.req(report));await h.service.save(h.req({...report,request_id:'request_123457'}));assert.equal((await h.service.list(h.req({}))).rows.length,2);});
for(const hours of [0,13,1.5,'3',null])test('reject invalid hours '+hours,async()=>{const h=harness();await assert.rejects(h.service.save(h.req({...report,hours})),{code:'invalid-argument'});});
for(const vehicle of ['', ' '.repeat(3),'x'.repeat(121),'bad\nname'])test('reject invalid vehicle '+vehicle.length,async()=>{const h=harness();await assert.rejects(h.service.save(h.req({...report,vehicle})),{code:'invalid-argument'});});
test('reject client identity/time/shift injection',async()=>{const h=harness();for(const key of ['uid','stationId','crew','created_at'])await assert.rejects(h.service.save(h.req({...report,[key]:'forged'})),{code:'invalid-argument'});});
test('inactive or stale-role identity cannot write or read',async()=>{const h=harness();h.state.get(h.root+'/users/actor123').is_active=false;await assert.rejects(h.service.save(h.req(report)),{code:'permission-denied'});await assert.rejects(h.service.list(h.req({})),{code:'permission-denied'});});
test('anonymous rejected',async()=>{const h=harness();await assert.rejects(h.service.context({data:{}}),{code:'unauthenticated'});});
test('missing crew rejects report',async()=>{const h=harness('firefighter','');await assert.rejects(h.service.save(h.req(report)),{code:'failed-precondition'});});
test('edit preserves creation/crew, revision and create-only audit; stale edit rejected',async()=>{const h=harness();const a=await h.service.save(h.req(report));const path=h.root+'/driving_refresh_reports/'+a.id,before=structuredClone(h.state.get(path));const edit={...report,request_id:'edit_request_123',report_id:a.id,revision:1,hours:5};await h.service.save(h.req(edit));await h.service.save(h.req(edit));const after=h.state.get(path);assert.equal(after.created_at,before.created_at);assert.equal(after.local_date,before.local_date);assert.equal(after.revision,2);assert.equal(after.hours,5);assert.equal([...h.state.keys()].filter(p=>p.includes('/edits/')).length,2);await assert.rejects(h.service.save(h.req({...edit,request_id:'edit_request_124'})),{code:'aborted'});});
test('cannot edit another driver',async()=>{const h=harness();h.seed('report_other123','other123','B',3);await assert.rejects(h.service.save(h.req({...report,report_id:'report_other123',revision:1})),{code:'permission-denied'});});
test('ordinary employee cannot read teammate or summary',async()=>{const h=harness();await assert.rejects(h.service.list(h.req({uid:'other123'})),{code:'permission-denied'});await assert.rejects(h.service.summary(h.req({month:'2026-10'})),{code:'permission-denied'});});
for(const role of ['commander','deputy'])test(role+' restricted to own crew and historical crew',async()=>{const h=harness(role);h.seed('report_good123','other123','B',3);h.seed('report_old123','other123','A',5);assert.equal((await h.service.list(h.req({uid:'other123'}))).rows.length,1);await assert.rejects(h.service.list(h.req({uid:'foreign123'})),{code:'permission-denied'});await assert.rejects(h.service.summary(h.req({month:'2026-10',crew:'A'})),{code:'permission-denied'});const sum=await h.service.summary(h.req({month:'2026-10'}));assert.equal(sum.hours,3);assert.equal(sum.count,1);assert.equal(sum.people.find(p=>p.uid==='other123').annual,true);});
test('station commander sees all three station crews and missing annual entries',async()=>{const h=harness('station_commander');h.seed('report_b123','other123','B',3);h.seed('report_a123','foreign123','A',6);const sum=await h.service.summary(h.req({month:'2026-10'}));assert.equal(sum.hours,9);assert.equal(sum.by_crew.A.hours,6);assert.equal(sum.by_crew.B.hours,3);assert.equal(sum.people.find(p=>p.uid==='actor123').annual,false);});
test('month totals use current edited hours, annual report includes earlier month',async()=>{const h=harness('deputy');h.seed('report_sep123','other123','B',4,'2026-09-30');const sum=await h.service.summary(h.req({month:'2026-10'}));assert.equal(sum.hours,0);assert.equal(sum.people.find(p=>p.uid==='other123').annual,true);});
test('history paginated with stable same-time tie breaker',async()=>{const h=harness();for(let i=0;i<31;i++)h.seed('report_'+String(i).padStart(8,'0'),'actor123','B',1);const first=await h.service.list(h.req({})),second=await h.service.list(h.req({cursor:first.next}));assert.equal(first.rows.length,PAGE);assert.equal(second.rows.length,6);assert.equal(new Set([...first.rows,...second.rows].map(r=>r.id)).size,31);assert.equal(second.next,null);});
test('invalid month and cursor fail closed',async()=>{const h=harness('deputy');await assert.rejects(h.service.summary(h.req({month:'2026-13'})),{code:'invalid-argument'});await assert.rejects(h.service.list(h.req({cursor:{at:'yesterday',id:'valid_id_123'}})),{code:'invalid-argument'});});
test('changed station claims do not read former station',async()=>{const h=harness();const req=h.req({});req.auth.token.stationId='another_station';await assert.rejects(h.service.list(req),{code:'permission-denied'});});
test('oversized summary refuses partial totals',async()=>{const h=harness('deputy');for(let i=0;i<5001;i++)h.seed('report_'+String(i).padStart(8,'0'),'other123','B',1);await assert.rejects(h.service.summary(h.req({month:'2026-10'})),{code:'resource-exhausted'});});
