'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
const sdkRequire=require('node:module').createRequire(path.resolve(__dirname,'./package.json'));
const {Firestore,Timestamp}=sdkRequire('firebase-admin/firestore');
const personContract=require('./schedule-person-contract');
const {createInvitations}=require('./invitations'),contract=require('./invitation-onboarding-contract');
const {createOnboardingStationGates}=require('./onboarding-station-gates');
const {stableHash}=require('./identity-coordinator');
const sdk=new Firestore({projectId:'demo-resq-station-gates'}),now=1790000000000;
const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const engine=createInvitations({clock:()=>now,randomBytes:crypto.randomBytes,createHash:sha,timingSafeEqual:crypto.timingSafeEqual,assertMayAssign(){},withinRoleSetterScope:()=>true});
function fixture({provisioning=false,person=false}={}){
 const uid='member_1',sid='station_1',pr='provision_20260915_1',request='request_20260915_001';
 const assignment={stationId:sid,districtId:'south',role:'commander',shift:'A',...(person?{person_id:'sp_person_0001'}:{})};
 const station=provisioning?{schema_version:1,station_id:sid,districtId:'south',name:'Test',active:false,silent:true,status:'provisioning',template_id:'fire-station-v1',provision_request_id:pr}:{districtId:'south',name:'Test',active:true};
 const invite={invite_id:'invite_1',secret_hash:sha('secret'),station_id:sid,district_id:'south',role:'commander',shift:'A',full_name:'Test Member',phone:'0500000000',email:'member@example.test',issued_by:'super_1',issued_at:Timestamp.fromMillis(now-1000),expires_at:Timestamp.fromMillis(now+60000),max_uses:1,...(person?{person_id:assignment.person_id}:{})};
 const redemption=engine.redeem(invite,'secret',{uid,email:invite.email,email_verified:true});
 const split=contract.splitRedemption({source:'server_document',invite,redeemed:redemption,recomputed_fingerprint:redemption.invite_fingerprint,auth:{uid,email:invite.email,email_verified:true},request_id:request});
 Object.assign(invite,{redeemed_by:uid,redeemed_request_id:request,redeemed_at:Timestamp.fromMillis(now)});
 const provision={schema_version:1,station_id:sid,request_id:pr,fingerprint:'a'.repeat(64),actor_uid:'super_1',first_admin_invitation_intent:{station_id:sid,district_id:'south',role:'commander',issued_by:'super_1',provision_request_id:pr},first_admin_invitation:{schema_version:1,station_id:sid,provision_request_id:pr,invite_id:invite.invite_id,invite_fingerprint:redemption.invite_fingerprint}};
 const registry={schema_version:1,uid,station_id:sid,request_id:request,invite_id:invite.invite_id,operation_fingerprint:split.operation_fingerprint};
 const onboarding={...registry,assignment_ref:split.assignment_ref,stage:'request_created'};
 const store=new Map([['stations/'+sid,station],['stations/'+sid+'/provision_operations/'+pr,provision],['invitations/invite_1',invite],['onboarding_assignment_links/'+uid,registry],['stations/'+sid+'/onboarding_operations/'+request,onboarding],['stations/'+sid+'/config/hr',{schema_version:1,email:null,name:null,hour_limit:null,seeded_by_request:pr}]]);
 const personRow={schema_version:1,person_id:'sp_person_0001',station_id:sid,kind:'external',linked_uid:null,display_name:'Test Member',active:true,revision:1,source_ref:{station_id:sid,source_namespace:'station-workbook-v1',source_key:{kind:'name',value:'Test Member'}}};
 if(person)store.set('stations/'+sid+'/schedule_people/'+personRow.person_id,personRow);
 const admin={uid:'super_1',disabled:false,customClaims:{super:true}},target={uid,email:invite.email,disabled:false,emailVerified:true,customClaims:{...assignment,emp:'601'}};
 const controls={cap:false,reads:0},db={doc:p=>sdk.doc(p)},tx={async get(ref){controls.reads++;return{exists:store.has(ref.path),data:()=>store.get(ref.path)};},set(){throw Error('write forbidden');},update(){throw Error('write forbidden');}};
 const auth={async getUser(id){return id===uid?target:admin;}},capability=async()=>controls.cap;
 const gates=createOnboardingStationGates({db,auth,personContract,invitations:engine,knownDistricts:['south'],readBackupCapability:capability,readHealthCapability:capability,readSilenceCapability:capability});
 const input={tx,uid,assignment,actor:{uid:'super_1'},phase:'initial'};
 function complete(){onboarding.stage='assignment_completed';onboarding.identity_operation_id='approve_1';invite.approved_identity_operation_id='approve_1';invite.approved_by='super_1';const source={schema_version:1,uid,registry_path:'onboarding_assignment_links/'+uid,operation_path:'stations/'+sid+'/onboarding_operations/'+request,invite_id:invite.invite_id,request_id:request,operation_fingerprint:registry.operation_fingerprint,invite_fingerprint:split.assignment_ref.invite_fingerprint,registration_fingerprint:split.assignment_ref.registration_fingerprint};const fingerprint=stableHash({assignment,source});invite.approved_source_fingerprint=fingerprint;store.set('identity_operations/'+uid,{status:'completed',target_uid:uid,op_id:'approve_1',actor_uid:'super_1',request_id:request,onboarding_authority:{assignment,source,fingerprint}});store.set('stations/'+sid+'/users/'+uid,{stationId:sid,districtId:'south',role:'commander',crew:'A',active:true,is_active:true,employee_number:'601'});store.set('stations/'+sid+'/roster/'+uid,{role:'commander',crew:'A',active:true,is_active:true});store.set('directory/'+uid,{station:sid,district:'south',role:'commander',crew:'A',active:true,is_active:true});store.set('emp_index/601',{uid,stationId:sid,active:true});}
  const completeWithTime=()=>{complete();invite.approved_at=Timestamp.fromMillis(now);};
  return{store,station,provision,invite,registry,onboarding,personRow,admin,target,controls,input,gates,complete:completeWithTime,run:()=>gates.requireStationPerson(input),ready:()=>gates.verifyReadiness({tx,station_id:sid,station,actor_uid:'super_1'})};
}
let passed=0;async function test(n,f){await f();passed++;console.log('PASS '+n);}
(async()=>{
 await test('active station and optional external person use actual person contract',async()=>{const f=fixture({person:true});assert.equal(await f.run(),true);assert.equal(f.personRow.linked_uid,null);});
 await test('first admin alone may enter silent inactive provisioned station',async()=>{const f=fixture({provisioning:true});assert.equal(await f.run(),true);assert.equal(f.station.active,false);assert.equal(f.station.silent,true);});
 await test('legacy station cannot contradict document station id',async()=>{const f=fixture();f.station.station_id='other';await assert.rejects(f.run);});
 for(const key of ['role','district_id','shift'])await test('provision binding rejects link '+key,async()=>{const f=fixture({provisioning:true});f.onboarding.assignment_ref={...f.onboarding.assignment_ref,[key]:'other'};await assert.rejects(f.run);});
 for(const[name,mutate]of Object.entries({district:f=>f.station.districtId='other',archived:f=>f.station.archived=true,activeShape:f=>f.station.active='true',partialMarker:f=>f.station.template_id='fire-station-v1',admin:f=>f.admin.customClaims.super=false,personMissing:f=>f.store.delete('stations/station_1/schedule_people/sp_person_0001'),personInactive:f=>f.personRow.active=false,personForeign:f=>f.personRow.station_id='station_2',personId:f=>f.personRow.person_id='sp_other_0001',personLinkedOther:f=>Object.assign(f.personRow,{kind:'registered',linked_uid:'other'})}))await test('normal gate denies '+name,async()=>{const f=fixture({person:true});mutate(f);await assert.rejects(f.run);});
 for(const[name,mutate]of Object.entries({association:f=>delete f.provision.first_admin_invitation,associationExtra:f=>f.provision.first_admin_invitation.extra=true,invite:f=>f.provision.first_admin_invitation.invite_id='other',fingerprint:f=>f.provision.first_admin_invitation.invite_fingerprint='0'.repeat(64),uid:f=>f.invite.redeemed_by='other',registry:f=>f.registry.station_id='other',role:f=>f.input.assignment.role='station_commander',silent:f=>f.station.silent=false,active:f=>f.station.active=true,revoked:f=>f.invite.revoked_at=Timestamp.fromMillis(now)}))await test('provision exception denies '+name,async()=>{const f=fixture({provisioning:true});mutate(f);await assert.rejects(f.run);});
 await test('missing capability remains unmet despite seed and completed first admin',async()=>{const f=fixture({provisioning:true});f.complete();const out=await f.ready();assert.equal(out.first_admin_active,true);assert.equal(out.hr_config_seeded,true);assert.equal(out.backup_registered,false);assert.equal(out.health_inventory_registered,false);assert.equal(out.silence_wired,false);});
 await test('required capability readers alone supply positive evidence in test',async()=>{const f=fixture({provisioning:true});f.complete();f.controls.cap=true;assert(Object.values(await f.ready()).every(v=>v===true));assert.equal(f.station.active,false);});
 for(const[name,mutate]of Object.entries({disabled:f=>f.target.disabled=true,role:f=>f.target.customClaims.role='firefighter',emp:f=>f.target.customClaims.emp='602',roster:f=>f.store.delete('stations/station_1/roster/member_1'),receipt:f=>f.invite.approved_identity_operation_id='other'}))await test('readiness refuses incomplete first admin '+name,async()=>{const f=fixture({provisioning:true});f.complete();mutate(f);assert.equal((await f.ready()).first_admin_active,false);});
 for(const[name,mutate]of Object.entries({missing:f=>f.store.delete('identity_operations/member_1'),actor:f=>f.store.get('identity_operations/member_1').actor_uid='other',source:f=>f.store.get('identity_operations/member_1').onboarding_authority.source.request_id='other',operation:f=>f.store.get('identity_operations/member_1').op_id='other',status:f=>f.store.get('identity_operations/member_1').status='processing',hash:f=>f.invite.approved_source_fingerprint='0'.repeat(64),target:f=>f.store.get('identity_operations/member_1').target_uid='other'}))await test('completed identity receipt denies '+name,async()=>{const f=fixture({provisioning:true});f.complete();mutate(f);assert.equal((await f.ready()).first_admin_active,false);});
 for(const[name,mutate]of Object.entries({email:f=>f.target.email='other@example.test',missingApprovalTime:f=>delete f.invite.approved_at,invalidApprovalTime:f=>f.invite.approved_at='not-a-timestamp'}))await test('readiness denies '+name,async()=>{const f=fixture({provisioning:true});f.complete();mutate(f);assert.equal((await f.ready()).first_admin_active,false);});
 console.log('Station gates: '+passed+' PASS (real engine/person contract + SDK refs, fake reads; emulator NOT RUN)');
})().catch(e=>{console.error(e);process.exitCode=1;});
