import {firebaseConfig} from './firebase-config.js?v=42h49';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import {getFunctions,httpsCallable} from './monitored-functions.js?v=42h49';
import {initAppCheck} from './appcheck.js?v=42h49';
import {renderNav,renderStuckNav} from './nav.js?v=42h49';
import {initPWA} from './pwa.js?v=42h49';
const $=id=>document.getElementById('drive-'+id),app=initializeApp(firebaseConfig);
await initAppCheck(app);const auth=getAuth(app),fns=getFunctions(app,'europe-west1');
const calls=Object.fromEntries(['getDrivingRefreshContext','saveDrivingRefreshReport','listDrivingRefreshReports','getDrivingRefreshSummary'].map(n=>[n,httpsCallable(fns,n)]));
let session=0,member=null,edit=null,busy=false,pending=null,ownCursor=null,historyCursor=null,target=null,readGeneration=0;
const crewLabel=c=>({A:'א׳',B:'ב׳',C:'ג׳'}[c]||'—');
const stamp=s=>new Intl.DateTimeFormat('he-IL',{timeZone:'Asia/Jerusalem',dateStyle:'short',timeStyle:'short'}).format(new Date(s));
const month=s=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit'}).format(new Date(s));
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function current(n){return session===n&&member&&auth.currentUser?.uid===member.uid;}
function message(error){const code=String(error?.code||'');return code.includes('permission-denied')?'אין הרשאה לדוח המבוקש או שהשיוך השתנה.':code.includes('aborted')?'הדיווח עודכן במקביל. טען מחדש לפני עריכה.':code.includes('resource-exhausted')?'הדוח גדול מדי לסיכום מלא. לא מוצג סיכום חלקי.':code.includes('failed-precondition')?'בדוק שיוך משמרת, שם משתמש ותקנון פעיל.':'הפעולה לא הושלמה. בשמירה ייתכן שהבקשה התקבלה — ניסיון חוזר לאותו דיווח משתמש באותו מזהה.';}
function view(name){readGeneration++;for(const key of ['report','mine','shift','history'])$(key).hidden=key!==name;$('status').textContent='';if(member)$('annual').textContent=(member.annual?'דווח השנה':'טרם דווח השנה')+' · '+(member.year||new Date(member.server_time).getFullYear())+' — אינו אישור כשירות.';}
function resetEdit(){edit=null;pending=null;$('vehicle').value='';$('hours').value='3';$('form-title').textContent='דיווח רענון נהיגה';$('cancel').hidden=true;}
function row(r,canEdit){const div=node('div');div.className='drive-item';div.append(node('strong',stamp(r.created_at)),node('p',r.vehicle+' · '+r.hours+' שעות · משמרת '+crewLabel(r.crew)));if(r.revision>1)div.append(node('small','נערך '+(r.revision-1)+' פעמים; מועד היצירה נשמר.'));if(canEdit){const button=node('button','עריכה');button.onclick=()=>{if(busy)return;edit=r;pending=null;view('report');$('vehicle').value=r.vehicle;$('hours').value=String(r.hours);$('form-title').textContent='עריכת דיווח מ־'+stamp(r.created_at);$('cancel').hidden=false;};div.append(button);}return div;}
async function loadList(history=false,more=false){const n=session,g=++readGeneration;const box=$(history?'history-list':'own-list'),button=$(history?'history-more':'own-more');if(!more){box.replaceChildren();button.hidden=true;}$('status').textContent='טוען דיווחים…';const data={};if(history)data.uid=target.uid;if(more)data.cursor=history?historyCursor:ownCursor;try{const result=(await calls.listDrivingRefreshReports(data)).data;if(!current(n)||g!==readGeneration)return;for(const r of result.rows)box.append(row(r,!history));if(!result.rows.length&&!more)box.append(node('p','אין דיווחים להצגה.'));if(history)historyCursor=result.next;else ownCursor=result.next;button.hidden=!result.next;$('status').textContent='';}catch(e){if(current(n)&&g===readGeneration)$('status').textContent=message(e);}}
async function summary(){const n=session,g=++readGeneration;$('roster').replaceChildren();$('summary').replaceChildren();$('status').textContent='טוען דוח…';try{const data={month:$('month').value};if($('crew').value)data.crew=$('crew').value;const r=(await calls.getDrivingRefreshSummary(data)).data;if(!current(n)||g!==readGeneration)return;const stats=node('div');stats.className='drive-stats';stats.append(node('strong',r.hours+' שעות'),node('strong',r.count+' דיווחים'));$('summary').append(stats,node('p',r.note));if(member.scope==='station'){const totals=node('p',Object.entries(r.by_crew).map(([c,v])=>'משמרת '+crewLabel(c)+': '+v.hours+' שעות, '+v.count+' דיווחים').join(' · '));$('summary').append(totals);}const table=node('table'),head=node('tr');for(const h of ['שם נהג','משמרת','דווח השנה','שעות היום','דיווחים החודש','שעות החודש'])head.append(node('th',h));table.append(head);for(const p of r.people){const tr=node('tr'),cell=node('td'),link=node('button',p.name||'ללא שם');link.className='drive-name';link.onclick=()=>{target=p;view('history');$('history-name').textContent='היסטוריית דיווחים — '+p.name;loadList(true);};cell.append(link);tr.append(cell);for(const value of [crewLabel(p.crew),p.annual?'כן':'טרם דווח',p.today_hours,p.count,p.hours])tr.append(node('td',String(value)));table.append(tr);}$('roster').append(table);$('status').textContent='';}catch(e){if(current(n)&&g===readGeneration)$('status').textContent=message(e);}}
for(let i=1;i<=12;i++){const o=node('option',i+' שעות');o.value=String(i);$('hours').append(o);}$('hours').value='3';
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(busy)return;view(b.dataset.view);if(b.dataset.view==='mine')loadList();if(b.dataset.view==='shift')summary();});
$('load').onclick=summary;$('own-more').onclick=()=>loadList(false,true);$('history-more').onclick=()=>loadList(true,true);$('back').onclick=()=>{view('shift');summary();};$('cancel').onclick=()=>{if(!busy)resetEdit();};
$('form').onsubmit=async e=>{e.preventDefault();if(busy||!member)return;const n=session,payload={vehicle:$('vehicle').value.trim(),hours:Number($('hours').value)};if(!payload.vehicle){$('status').textContent='חובה למלא שם רכב.';return;}if(edit){payload.report_id=edit.id;payload.revision=edit.revision;}const signature=JSON.stringify(payload);if(!pending||pending.signature!==signature)pending={signature,id:crypto.randomUUID()};busy=true;for(const control of $('form').elements)control.disabled=true;$('status').textContent='שומר…';try{await calls.saveDrivingRefreshReport({...payload,request_id:pending.id});if(!current(n))return;member.annual=true;resetEdit();$('status').textContent='הדיווח נשמר בהצלחה.';}catch(e){if(current(n))$('status').textContent=message(e);}finally{if(session===n){busy=false;for(const control of $('form').elements)control.disabled=false;}}};
renderStuckNav('driving-refresh.html');initPWA({offer:false});
onAuthStateChanged(auth,async user=>{const n=++session;member=null;readGeneration++;busy=false;edit=null;pending=null;ownCursor=null;historyCursor=null;target=null;$('work').hidden=true;$('own-list').replaceChildren();$('roster').replaceChildren();$('history-list').replaceChildren();$('summary').replaceChildren();$('identity').textContent='טוען…';resetEdit();for(const control of $('form').elements)control.disabled=false;if(!user){location.replace('login.html?next=driving-refresh.html');return;}try{const claims=(await user.getIdTokenResult()).claims;if(n!==session)return;const ctx=(await calls.getDrivingRefreshContext({})).data;if(n!==session||auth.currentUser?.uid!==user.uid)return;renderNav(claims,'driving-refresh.html',ctx.name);member={...ctx,uid:user.uid};$('identity').textContent=ctx.name+' · משמרת '+crewLabel(ctx.crew);$('time').textContent='שעון ישראל בעת פתיחת המסך: '+stamp(ctx.server_time)+'. זמן השמירה נקבע בשרת.';$('manager').hidden=ctx.scope==='self';$('crew').replaceChildren();if(ctx.scope==='station'){const all=node('option','כל המשמרות');all.value='';$('crew').append(all);}for(const c of ['A','B','C']){if(ctx.scope!=='station'&&c!==ctx.crew)continue;const o=node('option','משמרת '+crewLabel(c));o.value=c;$('crew').append(o);}$('month').value=month(ctx.server_time);$('work').hidden=false;view('report');}catch(e){if(n===session){$('identity').textContent='המסך אינו זמין לחשבון זה.';$('status').textContent=message(e);}}});
