import test from 'node:test';import assert from 'node:assert/strict';import {quotaStatus,planHandoff} from './night-planner.mjs';
const now=10000000;
const provider=(name='Gemini',remaining=50)=>({provider:name,connected:true,verifiedAt:now,quota:{provider:name,unit:'tokens',limit:100,remaining,observedAt:now,resetAt:now+60000}});
const args={preferred:'Claude',providers:[{...provider('Claude'),creditBlocked:true},provider()],chargedMicroUsd:1500000,now};
test('unavailable Claude routes advisory to actual named provider, not a fabricated Claude worker',()=>{const r=planHandoff(args);assert.equal(r.selected,'Gemini');assert.equal(r.handoff,true);assert.equal(r.automaticallyDispatched,false);assert.equal(r.requiresAtomicReservation,true);});
test('exact80percent rate threshold avoids that provider and emits warning',()=>{const r=planHandoff({...args,providers:[provider('Claude',20),provider('Grok')]});assert.equal(r.selected,'Grok');assert.ok(r.warnings.includes('Claude_RATE_LIMIT_80_PERCENT'));assert.equal(quotaStatus({...provider().quota,remaining:21},now).state,'AVAILABLE');});
test('missing stale future expired inconsistent quota never becomes capacity',()=>{for(const patch of [{},{...provider().quota,observedAt:now-60001},{...provider().quota,observedAt:now+1},{...provider().quota,resetAt:now},{...provider().quota,remaining:101},{...provider().quota,unit:'dollars'}])assert.equal(quotaStatus(patch,now).state,'UNKNOWN');assert.equal(planHandoff({...args,providers:[{...provider(),quota:undefined}]}).selected,null);});
test('shared80percent is explicitly reservation warning and no alternative bypasses hard/night cap',()=>{const r=planHandoff({...args,chargedMicroUsd:16000000,nightBaselineMicroUsd:15000000});assert.ok(r.warnings.includes('SHARED_RESERVATION_80_PERCENT'));for(const chargedMicroUsd of [3500000,20000000])assert.equal(planHandoff({...args,chargedMicroUsd}).selected,null);});
test('unknown identity, duplicate providers, invalid counters and mismatched snapshot rejected or unknown',()=>{for(const patch of [{chargedMicroUsd:NaN},{chargedMicroUsd:-1},{providers:[provider(),provider()]},{providers:[provider('Unknown')]},{nightLimitMicroUsd:2000001}])assert.throws(()=>planHandoff({...args,...patch}));assert.equal(planHandoff({...args,providers:[{...provider(),quota:provider('Grok').quota}]}).selected,null);});
